name: checkbox-mir
summary: Checkbox tests for the Mir project
description: |
  Collection of tests to be run on devices that are part of the mir project
version: git
confinement: strict
grade: stable

base: core22

plugs:
  checkbox-runtime:
    interface: content
    target: $SNAP/checkbox-runtime
    default-provider: checkbox22
  provider-resource:
    interface: content
    target: $SNAP/providers/checkbox-provider-resource
    default-provider: checkbox22
  provider-checkbox:
    interface: content
    target: $SNAP/providers/checkbox-provider-base
    default-provider: checkbox22
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

slots:
  wayland:
  x11:

layout:
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d
  /usr/share/X11:
    symlink: $SNAP/usr/share/X11
  /usr/lib/xorg:
    symlink: $SNAP/usr/lib/xorg
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts

environment:
  MIR_SERVER_PLATFORM_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform

apps:
  checkbox-cli:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: bin/checkbox-cli-wrapper
    plugs: &standard [home, network-bind, hardware-observe,
      mount-observe, network-manager, pulseaudio, serial-port,
      system-observe]
  checkbox-mir:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: bin/checkbox-mir
    plugs: *standard
  test-runner:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: bin/test-runner
    plugs: *standard
  service:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: bin/checkbox-cli-wrapper service
    daemon: simple
    restart-condition: on-failure
    plugs: *standard
  shell:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: bin/shell-wrapper
    plugs: *standard

parts:
  checkbox-provider-mir:
    plugin: dump
    source: ./
    source-type: local
    build-snaps:
      - checkbox-provider-tools
      - checkbox22
    override-build: |
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.8/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      # Comment out for now because it uses old tests to export paths
      # See: https://github.com/canonical/checkbox/blob/8cdd92cb7b02b64d76f4fe474569abb3f0d6f561/checkbox-core-snap/series22/snap/snapcraft.yaml#L397
      # for path in $(find "/snap/checkbox22/current/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      checkbox-provider-tools validate
      checkbox-provider-tools build
      checkbox-provider-tools install --layout=relocatable --prefix=/providers/checkbox-provider-mir --root="$SNAPCRAFT_PART_INSTALL"
    stage-packages:
      - lsof

  mir_demo_server:
    plugin: nil
    stage-packages:
      - mir-test-tools
      - mir-graphics-drivers-desktop
      - mir-graphics-drivers-nvidia
      - dmz-cursor-theme

  xorg:
    plugin: nil
    stage-packages:
      - xserver-xorg
      - x11-xkb-utils

  launchers:
    plugin: dump
    source: launchers/
    organize:
      '*': bin/

  graphics-core22:
    after: [mir_demo_server, xorg]
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
    prime:
    - bin/graphics-core22-wrapper
