name: checkbox-mir
summary: Checkbox tests for the Mir project
description: |
  Collection of tests to be run on devices that are part of the mir project
version: git
confinement: strict
grade: stable

base: core22

plugs:
  checkbox-runtime:
    interface: content
    target: $SNAP/checkbox-runtime
    default-provider: checkbox22
  provider-resource:
    interface: content
    target: $SNAP/providers/checkbox-provider-resource
    default-provider: checkbox22
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

layout:
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d
  /usr/share/X11:
    symlink: $SNAP/usr/share/X11
  /usr/lib/xorg:
    symlink: $SNAP/usr/lib/xorg

environment:
  MIR_SERVER_PLATFORM_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
  QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET}/qt5/plugins

apps:
  checkbox-cli:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: bin/checkbox-cli-wrapper
    plugs: &plugs [home, network-bind, hardware-observe,
      mount-observe, network-manager, pulseaudio, serial-port,
      system-observe, login-session-control, opengl]
    slots: &slots [wayslot, x11slot]
  graphics:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: bin/checkbox-graphics
    plugs: *plugs
    slots: *slots
  mir:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: bin/checkbox-mir
    plugs: *plugs
    slots: *slots
  mir-ci:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: providers/checkbox-provider-mir/bin/run_mir_ci.sh
    extensions: [gnome]
  snaps:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: bin/checkbox-snaps
    plugs: *plugs
  test-runner:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: bin/test-runner
    plugs: *plugs
    slots: *slots
  service:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: bin/checkbox-cli-wrapper service
    daemon: simple
    restart-condition: on-failure
    plugs: *plugs
    slots: *slots
  shell:
    command-chain: [bin/wrapper_local, bin/graphics-core22-wrapper]
    command: bin/shell-wrapper
    plugs: *plugs
    slots: *slots

slots:
  wayslot:
    interface: wayland
  x11slot:
    interface: x11

package-repositories:
  - type: apt
    ppa: mir-team/release

parts:
  checkbox-provider-mir:
    plugin: dump
    source: ./
    source-type: local
    build-snaps:
      - checkbox-provider-tools
      - checkbox22
    override-build: |
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.10/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      for path in $(find "/snap/checkbox22/current/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      checkbox-provider-tools validate
      checkbox-provider-tools build
      checkbox-provider-tools install --layout=relocatable --prefix=/providers/checkbox-provider-mir --root="$SNAPCRAFT_PART_INSTALL"
    stage-packages:
      - lsof

  mir_demo_server:
    plugin: nil
    stage-packages:
      - mir-test-tools
      - mir-graphics-drivers-desktop
      - mir-graphics-drivers-nvidia
      - dmz-cursor-theme

  xorg:
    plugin: nil
    stage-packages:
      - xserver-xorg
      - x11-xkb-utils

  launchers:
    plugin: dump
    source: launchers/
    organize:
      '*': bin/

  bits:
    plugin: nil
    stage-packages:
      - dpkg-dev
    prime:
      - usr/bin/dpkg-architecture

  mir-ci:
    plugin: python
    source: https://github.com/MirServer/mir-ci.git
    source-branch: make-package
    source-subdir: mir-ci
    python-packages:
    - asciinema
    - mypy
    - pywayland
    stage-packages:
    - libgtk-4-dev
    - python3-gi
    - pluma
    - qterminal
    - qtwayland5

  graphics-core22:
    after: [mir_demo_server, xorg, bits, mir-ci]
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
    prime:
    - bin/graphics-core22-wrapper
