name: Snap

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-pr${{ github.event.number }}
  cancel-in-progress: true

jobs:
  Snap:
    runs-on: ubuntu-latest

    timeout-minutes: 45

    strategy:
      fail-fast: false
      matrix:
        architecture:
        - amd64
        - armhf
        - arm64

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # needed for version determination

    - name: Patch PPA and version
      run: |
        sed -i 's@mir-team/release@mir-team/dev@' snap/snapcraft.yaml

    - name: Build and publish the snap
      uses: canonical/actions/build-snap@release
      with:
        architecture: ${{ matrix.architecture }}
        snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
        launchpad-credentials: ${{ secrets.LAUNCHPAD_CREDENTIALS }}
        launchpad-accept-public-upload: true
        publish: ${{ github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name }}
        publish-channel: edge/pr${{ github.event.number }}
